/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_api_repositories_get"];
        put?: never;
        /**
         * Add Repository
         * @description Register a local repository and start (or incrementally update) its analysis.
         */
        post: operations["add_repository_api_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository */
        get: operations["get_repository_api_repositories__repo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_repositories__repo_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_repositories__repo_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/developers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Developers
         * @description Per-developer metrics (ranked by commits only as a default sort, not a score).
         */
        get: operations["developers_api_repositories__repo_id__developers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/developers/{dev_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Developer */
        get: operations["developer_api_repositories__repo_id__developers__dev_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["activity_api_repositories__repo_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Files */
        get: operations["files_api_repositories__repo_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Commits */
        get: operations["list_commits_api_repositories__repo_id__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repo_id}/commits/{sha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commit Detail */
        get: operations["commit_detail_api_repositories__repo_id__commits__sha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Buckets */
            buckets: components["schemas"]["ActivityBucket"][];
        };
        /** ActivityBucket */
        ActivityBucket: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Commits */
            commits: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
        };
        /** ChangedFile */
        ChangedFile: {
            /** Path */
            path: string;
            /** Old Path */
            old_path: string | null;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
            /** Is Binary */
            is_binary: boolean;
        };
        /** CommitDetail */
        CommitDetail: {
            /** Sha */
            sha: string;
            /** Short Sha */
            short_sha: string;
            /** Author Name */
            author_name: string;
            /** Author Email */
            author_email: string;
            /** Developer Id */
            developer_id: number;
            /**
             * Authored At
             * Format: date-time
             */
            authored_at: string;
            /** Message */
            message: string;
            /** Files Changed */
            files_changed: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
            /** Files */
            files: components["schemas"]["ChangedFile"][];
        };
        /** CommitList */
        CommitList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["CommitOut"][];
        };
        /** CommitOut */
        CommitOut: {
            /** Sha */
            sha: string;
            /** Short Sha */
            short_sha: string;
            /** Author Name */
            author_name: string;
            /** Author Email */
            author_email: string;
            /** Developer Id */
            developer_id: number;
            /**
             * Authored At
             * Format: date-time
             */
            authored_at: string;
            /** Message */
            message: string;
            /** Files Changed */
            files_changed: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
        };
        /** DeveloperStats */
        DeveloperStats: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Commits */
            commits: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
            /** Files Touched */
            files_touched: number;
            /** First Commit At */
            first_commit_at: string | null;
            /** Last Commit At */
            last_commit_at: string | null;
        };
        /** FileList */
        FileList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["FileStats"][];
        };
        /** FileStats */
        FileStats: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Commits */
            commits: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
            /** Developers */
            developers: number;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RepositoryCreate */
        RepositoryCreate: {
            /** Path */
            path: string;
        };
        /** RepositoryOut */
        RepositoryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "ready" | "failed";
            /** Error */
            error: string | null;
            /** Commits Total */
            commits_total: number;
            /** Commits Processed */
            commits_processed: number;
            /** Last Analyzed Sha */
            last_analyzed_sha: string | null;
            /** Last Analyzed At */
            last_analyzed_at: string | null;
            /** Is Shallow */
            is_shallow: boolean;
        };
        /** Summary */
        Summary: {
            /** Commits */
            commits: number;
            /** Developers */
            developers: number;
            /** Files Modified */
            files_modified: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
            /** First Commit At */
            first_commit_at: string | null;
            /** Last Commit At */
            last_commit_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_repositories_api_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"][];
                };
            };
        };
    };
    add_repository_api_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_api_repositories__repo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_repositories__repo_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_repositories__repo_id__summary_get: {
        parameters: {
            query?: {
                /** @description UTC date, inclusive */
                from?: string | null;
                /** @description UTC date, inclusive */
                to?: string | null;
                developer_id?: number[] | null;
            };
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    developers_api_repositories__repo_id__developers_get: {
        parameters: {
            query?: {
                /** @description UTC date, inclusive */
                from?: string | null;
                /** @description UTC date, inclusive */
                to?: string | null;
                developer_id?: number[] | null;
            };
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeveloperStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    developer_api_repositories__repo_id__developers__dev_id__get: {
        parameters: {
            query?: {
                /** @description UTC date, inclusive */
                from?: string | null;
                /** @description UTC date, inclusive */
                to?: string | null;
                developer_id?: number[] | null;
            };
            header?: never;
            path: {
                dev_id: number;
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeveloperStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_api_repositories__repo_id__activity_get: {
        parameters: {
            query?: {
                granularity?: "auto" | "day" | "week" | "month";
                /** @description UTC date, inclusive */
                from?: string | null;
                /** @description UTC date, inclusive */
                to?: string | null;
                developer_id?: number[] | null;
            };
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    files_api_repositories__repo_id__files_get: {
        parameters: {
            query?: {
                q?: string | null;
                sort?: "commits" | "additions" | "deletions" | "developers" | "last_modified";
                limit?: number;
                offset?: number;
                /** @description UTC date, inclusive */
                from?: string | null;
                /** @description UTC date, inclusive */
                to?: string | null;
                developer_id?: number[] | null;
            };
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commits_api_repositories__repo_id__commits_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
                /** @description UTC date, inclusive */
                from?: string | null;
                /** @description UTC date, inclusive */
                to?: string | null;
                developer_id?: number[] | null;
            };
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_detail_api_repositories__repo_id__commits__sha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha: string;
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
